language: php
php:
    - 7.1

sudo: required
services:
    - docker

before_script:
    - docker-compose build
    - docker-compose create
    - docker-compose start
    - docker-compose ps

script:
    - docker-compose run php ./vendor/bin/drupal alice:load-fixtures  --verbose  modules/dtl_alice_fixtures/example/set1 --purge
